config/routes.rb
Rails.application.routes.draw do
  # get 'articles/index'

  # get 'articles/show'

  # get 'articles/new'

  # get 'articles/create'

  # get 'articles/edit'

  # get 'articles/update'

  # get 'articles/destory'

  # get 'index/show'

  # get 'index/new'

  # get 'index/create'

  # get 'index/edit'

  # get 'index/update'

  # get 'index/destory'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @articles = Article.new
  end

  def create
    Article.create(article_params)
    redirect_to articles_path
  end

  def edit
  end

  def update
    @article.update(article_params)
    redirect_to articles_path
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/views/articles/edit.html.erb
<div class="container">
<h1>Edit Articles</h1>
<%= form_for(@article) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.submit %>
<% end %>
</div>

app/views/articles/index.html.erb
<div class="container">
<h1>Rails Wikinimious</h1>
<ul>
<% @articles.each do |article| %>

  <li><%= (Kramdown::Document.new(article.title).to_html).html_safe %>
    <%= link_to "show", article_path(article) %>
    <%= link_to "destroy", article_path(article), method: :delete  %>
    <%= link_to "edit", edit_article_path(article)  %>
  </li>

<% end %>
</ul>
<%= link_to "new_article", new_article_path %>
</div>

app/views/articles/new.html.erb
<div class="container">
<h1>Add New Article</h1>
<%= form_for(@articles) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.submit %>
<% end %>
</div>

app/views/articles/show.html.erb
<% article_title = Kramdown::Document.new(@article.title).to_html %>
<% article_content = Kramdown::Document.new(@article.content).to_html %>

<div class="container">
<h1>Show Article</h1>
<h2><%= article_title.html_safe %></h2>
<p><%= article_content.html_safe %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>